FROM node:20.12.2-alpine3.18

WORKDIR /app

# Check is yarn install in global.
RUN if ! command -v yarn &> /dev/null; then \
    npm install -g yarn; \
    fi

COPY package.json yarn.lock ./

COPY . . 

RUN yarn install 

CMD ["yarn", "dev"] 