version: "3.8"
services:
  local:
    container_name: fe-local
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - ./:/app # For hot reloading
      - node_modules:/app/node_modules
volumes:
  node_modules:
